#!/usr/bin/env bash
# shellcheck shell=bash
# Generate WireGuard configs and keys into a staging directory.

# shellcheck source=common.sh
# shellcheck source=nat.sh

wg_stage_dir=""

wg_prepare_stage() {
  wg_stage_dir="$(mktemp -d "${TMPDIR:-/tmp}/wireconf.XXXXXX")"
  chmod 700 "$wg_stage_dir"
  trap 'wg_cleanup_stage' EXIT
}

wg_cleanup_stage() {
  [[ -n "${wg_stage_dir:-}" && -d "$wg_stage_dir" ]] && rm -rf "$wg_stage_dir"
}

wg_gen_keypair_local() {
  local priv="$1"
  local pub="$2"
  wg genkey | tee "$priv" | wg pubkey >"$pub"
  chmod 600 "$priv"
  chmod 600 "$pub"
}

# Use inventory hub (first line) over SSH when the operator has no wg.
wg_gen_keypair_via_hub() {
  local ht="$1" hp="$2" priv="$3" pub="$4"
  local key
  IFS= read -r key < <(wc_ssh_exec "$ht" "$hp" "wg genkey") || die "wg genkey failed on hub ${ht}"
  [[ -n "$key" ]] || die "wg genkey returned empty output on hub ${ht}"
  printf '%s\n' "$key" >"$priv"
  chmod 600 "$priv"
  printf '%s\n' "$key" | wc_ssh_exec "$ht" "$hp" "wg pubkey" >"$pub"
  chmod 600 "$pub"
}

# Outputs path to generated conf for host index i
wg_conf_path_for_index() {
  printf '%s/host-%s.conf' "$wg_stage_dir" "$1"
}

wg_build_all() {
  local n="${#WC_SSH_TARGETS[@]}"
  local i priv pub hub_priv hub_pub
  local pfx
  pfx="$(cidr_prefix_len "$WC_NETWORK")"

  wc_resolve_hub_endpoint_from_inventory || true

  wg_prepare_stage

  for ((i = 0; i < n; i++)); do
    priv="$wg_stage_dir/host-$i.privatekey"
    pub="$wg_stage_dir/host-$i.publickey"
    if [[ "${WC_KEYGEN_MODE:-local}" == "remote_hub" ]]; then
      wg_gen_keypair_via_hub "${WC_SSH_TARGETS[0]}" "${WC_SSH_PORTS[0]}" "$priv" "$pub"
    else
      wg_gen_keypair_local "$priv" "$pub"
    fi
  done

  hub_priv="$wg_stage_dir/host-0.privatekey"
  hub_pub="$wg_stage_dir/host-0.publickey"

  local hub_ip peer_ip peer_pub
  hub_ip="${WC_INDEX_TO_IP[0]}/${pfx}"

  local hub_conf
  hub_conf="$(wg_conf_path_for_index 0)"
  {
    echo "# Generated by wireconf — hub"
    echo "[Interface]"
    echo "Address = ${hub_ip}"
    echo "ListenPort = ${WC_PORT}"
    echo "PrivateKey = $(cat "$hub_priv")"
    [[ -n "${WC_MTU:-}" ]] && echo "MTU = ${WC_MTU}"
    if any_full_tunnel_peer; then
      echo "PostUp = $(nat_post_up_line "$WC_IFACE")"
      echo "PostDown = $(nat_post_down_line "$WC_IFACE")"
    fi
    for ((i = 1; i < n; i++)); do
      peer_ip="${WC_INDEX_TO_IP[$i]}"
      peer_pub="$(cat "$wg_stage_dir/host-$i.publickey")"
      echo
      echo "[Peer]"
      echo "PublicKey = ${peer_pub}"
      echo "AllowedIPs = ${peer_ip}/32"
    done
  } >"$hub_conf"

  for ((i = 1; i < n; i++)); do
    local pc peer_priv p_pub
    peer_ip="${WC_INDEX_TO_IP[$i]}/${pfx}"
    peer_priv="$wg_stage_dir/host-$i.privatekey"
    p_pub="$(cat "$hub_pub")"
    pc="$(wg_conf_path_for_index "$i")"
    local allowed
    if [[ "${WC_FULL_TUNNEL[$i]}" == "yes" ]]; then
      allowed="0.0.0.0/0"
    else
      allowed="${WC_NETWORK}"
    fi
    {
      echo "# Generated by wireconf — peer (hub index 0)"
      echo "[Interface]"
      echo "Address = ${peer_ip}"
      echo "PrivateKey = $(cat "$peer_priv")"
      [[ -n "${WC_MTU:-}" ]] && echo "MTU = ${WC_MTU}"
      if [[ "${WC_FULL_TUNNEL[$i]}" == "yes" && -n "${WC_PEER_DNS:-}" ]]; then
        echo "DNS = ${WC_PEER_DNS}"
      elif [[ "${WC_FULL_TUNNEL[$i]}" != "yes" && -n "${WC_SPLIT_DNS:-}" ]]; then
        echo "DNS = ${WC_SPLIT_DNS}"
      fi
      echo
      echo "[Peer]"
      echo "PublicKey = ${p_pub}"
      echo "Endpoint = ${WC_HUB_ENDPOINT}:${WC_PORT}"
      echo "AllowedIPs = ${allowed}"
      if [[ "${WC_KEEPALIVE}" -gt 0 ]]; then
        echo "PersistentKeepalive = ${WC_KEEPALIVE}"
      fi
    } >"$pc"
  done
}
