#!/usr/bin/env bash
# shellcheck shell=bash
# Produce a single-file wireconf by inlining lib/*.sh and embedding examples/.
#
# Usage: scripts/build-single-file.sh [OUT_DIR]
#   OUT_DIR defaults to ./dist next to the repo root.
#
# Output: ${OUT_DIR}/wireconf (chmod 0755) and ${OUT_DIR}/wireconf.sha256.
set -euo pipefail

_BUILD_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_DIR="${1:-${_BUILD_ROOT}/dist}"
OUT="${OUT_DIR}/wireconf"

[[ -f "${_BUILD_ROOT}/wireconf" ]] || {
  printf 'build: cannot find %s/wireconf\n' "$_BUILD_ROOT" >&2
  exit 1
}
[[ -d "${_BUILD_ROOT}/lib" ]] || {
  printf 'build: cannot find %s/lib/\n' "$_BUILD_ROOT" >&2
  exit 1
}
[[ -d "${_BUILD_ROOT}/examples" ]] || {
  printf 'build: cannot find %s/examples/\n' "$_BUILD_ROOT" >&2
  exit 1
}

mkdir -p "$OUT_DIR"

VERSION="$(awk -F'"' '/^WIRECONF_VERSION=/ {print $2; exit}' "${_BUILD_ROOT}/wireconf")"
[[ -n "$VERSION" ]] || { echo "build: could not read WIRECONF_VERSION" >&2; exit 1; }

COMMIT="$(git -C "$_BUILD_ROOT" rev-parse --short HEAD 2>/dev/null || echo unknown)"
DATE="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

# Emit the body of a lib file, stripping shebang and `# shellcheck shell=`/`# shellcheck source=`
# directives (the former is noise inside a single file, the latter references paths that no
# longer exist). Other shellcheck directives (disable=, enable=) are kept — they are functional.
_inline_lib() {
  local f="$1" first=1 line
  printf '\n# --- inlined: lib/%s ---\n' "$(basename "$f")"
  while IFS= read -r line || [[ -n "$line" ]]; do
    if [[ $first -eq 1 ]]; then
      first=0
      [[ "$line" == "#!"* ]] && continue
    fi
    case "$line" in
      '# shellcheck shell='* | '# shellcheck source='*) continue ;;
      *) printf '%s\n' "$line" ;;
    esac
  done <"$f"
}

# Process the wireconf entry script:
#   - strip the shebang (a custom one is emitted by main)
#   - strip `# shellcheck shell=` / `# shellcheck source=` directives
#   - drop the now-unused `_WIRECONF_ROOT=` assignment
#   - replace each `source "$_WIRECONF_ROOT/lib/NAME.sh"` line with that file's body
#   - replace the `wc_embedded_examples_dir` block with a single-file version that
#     writes heredocs at runtime
# Case patterns use single quotes around literal glob text with `$_WIRECONF_ROOT`;
# single-quoting is intentional, SC2016 does not apply.
# shellcheck disable=SC2016
_process_wireconf() {
  local first=1 line path in_embed=0
  while IFS= read -r line || [[ -n "$line" ]]; do
    if [[ $first -eq 1 ]]; then
      first=0
      [[ "$line" == "#!"* ]] && continue
    fi

    if [[ $in_embed -eq 1 ]]; then
      if [[ "$line" == "# WIRECONF_EMBED_EXAMPLES_END" ]]; then
        in_embed=0
      fi
      continue
    fi

    case "$line" in
      '# WIRECONF_EMBED_EXAMPLES_START')
        in_embed=1
        _emit_embedded_examples_dir
        continue
        ;;
      '# shellcheck shell='* | '# shellcheck source='*)
        continue
        ;;
      '_WIRECONF_ROOT='*)
        continue
        ;;
      'source "$_WIRECONF_ROOT/lib/'*'"')
        path="${line#source \"\$_WIRECONF_ROOT/}"
        path="${path%\"}"
        [[ -f "${_BUILD_ROOT}/${path}" ]] || {
          printf 'build: missing lib file referenced by wireconf: %s\n' "$path" >&2
          exit 1
        }
        _inline_lib "${_BUILD_ROOT}/${path}"
        ;;
      *)
        printf '%s\n' "$line"
        ;;
    esac
  done <"${_BUILD_ROOT}/wireconf"
}

# Emit a runtime-heredoc version of wc_embedded_examples_dir that writes the
# example files to a fresh mktemp tree. Quoted delimiters keep $VAR literal.
_emit_embedded_examples_dir() {
  cat <<'OUTER_EOF'
wc_embedded_examples_dir() {
  local d
  d="$(mktemp -d "${TMPDIR:-/tmp}/wireconf-ex.XXXXXX")"
  cat >"${d}/inventory.example" <<'WIRECONF_INVENTORY_EXAMPLE_EOF'
OUTER_EOF
  cat "${_BUILD_ROOT}/examples/inventory.example"
  cat <<'OUTER_EOF'
WIRECONF_INVENTORY_EXAMPLE_EOF
  cat >"${d}/wireconf.env.example" <<'WIRECONF_ENV_EXAMPLE_EOF'
OUTER_EOF
  cat "${_BUILD_ROOT}/examples/wireconf.env.example"
  cat <<'OUTER_EOF'
WIRECONF_ENV_EXAMPLE_EOF
  echo "$d"
}
OUTER_EOF
}

_emit_header() {
  cat <<HEADER_EOF
#!/usr/bin/env bash
# shellcheck shell=bash
# shellcheck disable=SC2034
# wireconf ${VERSION} — single-file build (commit ${COMMIT}, built ${DATE})
# Generated by scripts/build-single-file.sh. Do not edit by hand.
WIRECONF_SINGLE_FILE=1
HEADER_EOF
}

{
  _emit_header
  _process_wireconf
} >"$OUT"

chmod 0755 "$OUT"

# Compute a sha256 sidecar. Use sha256sum when available; otherwise shasum -a 256.
if command -v sha256sum >/dev/null 2>&1; then
  ( cd "$OUT_DIR" && sha256sum "$(basename "$OUT")" >"$(basename "$OUT").sha256" )
elif command -v shasum >/dev/null 2>&1; then
  ( cd "$OUT_DIR" && shasum -a 256 "$(basename "$OUT")" >"$(basename "$OUT").sha256" )
else
  printf 'build: neither sha256sum nor shasum found; skipping checksum\n' >&2
fi

lines="$(wc -l <"$OUT" | tr -d ' ')"
bytes="$(wc -c <"$OUT" | tr -d ' ')"
printf 'Built %s (v%s, %s lines, %s bytes)\n' "$OUT" "$VERSION" "$lines" "$bytes"
